name: Asciidoctor Demo
on: [push]
jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - uses: reitzig/actions-asciidoctor@v2.0.1
        with:
          version: 2.0.18

      - run: asciidoctor --version
      - run: asciidoctor-pdf -v